/**
 * Application-wide constants
 * Auto-generated by Code Janitor
 */

// File Size Limits
export const MAX_FILE_SIZE = 10 * 1024 * 1024 // 10MB
export const MAX_IMAGE_SIZE = 5 * 1024 * 1024 // 5MB
export const MIN_FILE_SIZE = 1024 // 1KB

// Pagination
export const DEFAULT_PAGE_SIZE = 10
export const MAX_PAGE_SIZE = 100
export const DEFAULT_PAGE = 1

// Timeouts
export const DEFAULT_TIMEOUT = 30000 // 30 seconds
export const UPLOAD_TIMEOUT = 120000 // 2 minutes
export const API_TIMEOUT = 10000 // 10 seconds

// Business Logic
export const TAX_RATE = 0.0825 // 8.25%
export const MIN_ORDER_AMOUNT = 10.00
export const MAX_ORDER_AMOUNT = 10000.00
export const DEFAULT_CURRENCY = 'USD'

// UI Constants
export const DEBOUNCE_DELAY = 300 // milliseconds
export const TOAST_DURATION = 5000 // 5 seconds
export const ANIMATION_DURATION = 200 // milliseconds

// Shipping
export const MAX_WEIGHT_LBS = 150
export const MIN_WEIGHT_LBS = 0.1
export const DEFAULT_WAREHOUSE_ZIP = '75001'

// Cache
export const CACHE_TTL = 15 * 60 * 1000 // 15 minutes
export const SESSION_TTL = 24 * 60 * 60 * 1000 // 24 hours
