#!/bin/bash

echo "🔄 N8N Workflow Import Script"
echo "=============================="
echo ""
echo "This script will guide you through importing the 8 marketing automation workflows."
echo ""

# Workflow files
WORKFLOW_DIR="/root/websites/gangrunprinting/n8n-workflows"
WORKFLOWS=(
  "1-abandoned-cart-3hr.json"
  "2-abandoned-cart-24hr.json"
  "3-abandoned-cart-72hr.json"
  "4-winback-campaign.json"
  "5-order-anniversaries.json"
  "6-review-collection.json"
  "7-post-purchase-webhook.json"
  "8-order-delivered-webhook.json"
)

echo "📁 Workflow files location: $WORKFLOW_DIR"
echo ""
echo "Found ${#WORKFLOWS[@]} workflow files:"
for i in "${!WORKFLOWS[@]}"; do
  echo "  $((i+1)). ${WORKFLOWS[$i]}"
done
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 MANUAL IMPORT INSTRUCTIONS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Since N8N requires browser-based authentication, please follow these steps:"
echo ""
echo "1️⃣  Open N8N in your browser:"
echo "    https://n8n.agistaffers.com"
echo ""
echo "2️⃣  Log in with your credentials"
echo ""
echo "3️⃣  For EACH of the 8 workflow files above:"
echo ""
echo "    a) Click 'Workflows' in the sidebar"
echo "    b) Click '+ Add workflow' button (top right)"
echo "    c) Click the 3-dot menu (⋮) in top right"
echo "    d) Select 'Import from File'"
echo "    e) Navigate to: $WORKFLOW_DIR"
echo "    f) Select the workflow JSON file"
echo "    g) Click 'Open'"
echo "    h) The workflow will load - click 'Save' (top right)"
echo "    i) Rename if needed (name is in the JSON)"
echo ""
echo "4️⃣  After importing all 8 workflows:"
echo ""
echo "    a) Go to 'Workflows' page"
echo "    b) Toggle each workflow to 'Active' (green switch)"
echo ""
echo "5️⃣  Verify the workflows:"
echo ""
echo "    a) Check cron schedules are correct"
echo "    b) Check webhook URLs match database"
echo "    c) Execute a workflow manually to test"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 WORKFLOW SUMMARY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "CRON WORKFLOWS (Scheduled):"
echo "  ├─ Abandoned Cart (3hr)    - Every hour (0 * * * *)"
echo "  ├─ Abandoned Cart (24hr)   - Every hour (0 * * * *)"
echo "  ├─ Abandoned Cart (72hr)   - Every hour (0 * * * *)"
echo "  ├─ Win-back Campaign       - Daily 10 AM (0 10 * * *)"
echo "  ├─ Order Anniversaries     - Daily 9 AM (0 9 * * *)"
echo "  └─ Review Collection       - Daily 2 PM (0 14 * * *)"
echo ""
echo "WEBHOOK WORKFLOWS (Real-time):"
echo "  ├─ Post-Purchase Thank You - /webhook/gangrun-order-created"
echo "  └─ Order Delivered Review  - /webhook/gangrun-order-delivered"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📖 FULL DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Detailed import guide:"
echo "  /root/websites/gangrunprinting/docs/N8N-WORKFLOW-IMPORT-INSTRUCTIONS.md"
echo ""
echo "Configuration summary:"
echo "  /root/websites/gangrunprinting/docs/N8N-CONFIGURATION-COMPLETE.md"
echo ""
echo "Location guide:"
echo "  /root/websites/gangrunprinting/docs/WHERE-IS-MARKETING-AUTOMATION.md"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ All workflow files are ready for import!"
echo ""
echo "Next step: Open https://n8n.agistaffers.com and follow the instructions above."
echo ""
