version: '3.8'

networks:
  printshop_dev:
    driver: bridge

services:
  # PostgreSQL Database for Development
  postgres-dev:
    container_name: gangrunprinting_postgres_dev
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=printshop_user
      - POSTGRES_PASSWORD=printshop_password
      - POSTGRES_DB=printshop_db
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - printshop_dev
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U printshop_user -d printshop_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO Object Storage for Development
  minio-dev:
    container_name: gangrunprinting_minio_dev
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin_password
    volumes:
      - minio_dev_data:/data
    networks:
      - printshop_dev
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_dev_data:
  minio_dev_data: