version: '3.8'

# Production Monitoring Stack for GangRun Printing
# Simplified for initial deployment

services:
  # ========================================
  # PROMETHEUS - Metrics Collection
  # ========================================
  prometheus:
    image: prom/prometheus:latest
    container_name: gangrun_prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
      - /opt/gangrun/monitoring/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring

  # ========================================
  # GRAFANA - Visualization
  # ========================================
  grafana:
    image: grafana/grafana:latest
    container_name: gangrun_grafana
    restart: unless-stopped
    ports:
      - "3010:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=GangRun2024Monitor!
      - GF_INSTALL_PLUGINS=redis-datasource,grafana-piechart-panel
      - GF_SERVER_ROOT_URL=http://gangrunprinting.com:3010
    volumes:
      - /opt/gangrun/monitoring/grafana:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring

  # ========================================
  # ALERTMANAGER - Alert Management
  # ========================================
  alertmanager:
    image: prom/alertmanager:latest
    container_name: gangrun_alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager/alertmanager-simple.yml:/etc/alertmanager/alertmanager.yml:ro
      - /opt/gangrun/monitoring/alertmanager:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring

  # ========================================
  # NODE EXPORTER - System Metrics
  # ========================================
  node-exporter:
    image: prom/node-exporter:latest
    container_name: gangrun_node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge