#!/usr/bin/env tsx
/**
 * Southwest Cargo Airport Data Migration Script
 * Imports all 82 Southwest Cargo airport locations
 * Run with: npx tsx src/scripts/seed-southwest-airports.ts
 *
 * DATA SOURCE: Definitive list provided October 17, 2025
 * This is the ONLY source of Southwest Cargo airport data
 * NO hardcoded arrays should exist anywhere else in the codebase
 */

import { PrismaClient, Carrier } from '@prisma/client'
import { randomUUID } from 'crypto'

const prisma = new PrismaClient()

interface AirportData {
  code: string
  name: string
  operator?: string
  address: string
  city: string
  state: string
  zip: string
  hours: Record<string, string>
}

const SOUTHWEST_CARGO_AIRPORTS: AirportData[] = [
  {
    code: 'ALB',
    name: 'Albany',
    operator: 'Mobile Air Transport',
    address: '46 Kelly Rd',
    city: 'Latham',
    state: 'NY',
    zip: '12110',
    hours: { 'Mon-Fri': '5:00am-9:00pm', 'Sat-Sun': 'Closed' },
  },
  {
    code: 'ABQ',
    name: 'Albuquerque',
    address: '2200 Sunport Blvd (Bay F)',
    city: 'Albuquerque',
    state: 'NM',
    zip: '87106',
    hours: { 'Mon-Fri': '5:00am-12:00am', 'Sat-Sun': '5:30am-9:00pm' },
  },
  {
    code: 'AMA',
    name: 'Amarillo',
    address: '10801 Airport Blvd',
    city: 'Amarillo',
    state: 'TX',
    zip: '79111',
    hours: { 'Mon-Fri': '6:00am-10:45pm', 'Sat': '7:00am-3:30pm', 'Sun': '9:00am-8:00pm' },
  },
  {
    code: 'ATL',
    name: 'Atlanta',
    address: '3400 Interloop Rd, Space G2-Cargo',
    city: 'Atlanta',
    state: 'GA',
    zip: '30354',
    hours: { 'Mon-Fri': '5:00am-12:00am', 'Sat-Sun': '5:00am-11:00pm' },
  },
  {
    code: 'AUS',
    name: 'Austin',
    address: '3400 Spirit of Texas Dr Ste 250',
    city: 'Austin',
    state: 'TX',
    zip: '78719',
    hours: { 'Mon-Fri': '4:30am-1:30am', 'Sat': '5:30am-9:00pm', 'Sun': '4:30am-9:00pm' },
  },
  {
    code: 'BWI',
    name: 'Baltimore/Washington',
    address: 'BWI Building C, Air Cargo Drive',
    city: 'Linthicum',
    state: 'MD',
    zip: '21240',
    hours: { 'Mon': '5:00am-12:00am', 'Tue-Fri': 'Open 24 hours', 'Sat': '12:00am-8:00pm', 'Sun': '5:00am-8:00pm' },
  },
  {
    code: 'BHM',
    name: 'Birmingham',
    address: '1710 40th St N Ste C',
    city: 'Birmingham',
    state: 'AL',
    zip: '35217',
    hours: { 'Mon-Fri': '4:45am-9:45pm', 'Sat': '5:00am-8:00pm', 'Sun': '5:00am-7:30pm' },
  },
  {
    code: 'BOS',
    name: 'Boston',
    address: '112 Harborside Dr South Cargo Bldg 63',
    city: 'Boston',
    state: 'MA',
    zip: '02128',
    hours: { 'Mon-Fri': '4:30am-12:00am', 'Sat': '5:00am-7:00pm', 'Sun': '5:00am-5:00pm' },
  },
  {
    code: 'BUF',
    name: 'Buffalo',
    address: '281 Cayuga Rd',
    city: 'Buffalo',
    state: 'NY',
    zip: '14225',
    hours: { 'Mon-Fri': '6:00am-11:00pm', 'Sat-Sun': '6:00am-1:30pm' },
  },
  {
    code: 'BUR',
    name: 'Burbank',
    address: '4209 Empire Ave',
    city: 'Burbank',
    state: 'CA',
    zip: '91505',
    hours: { 'Mon-Fri': '5:30am-10:30pm', 'Sat-Sun': '6:30am-6:30pm' },
  },
  {
    code: 'CHS',
    name: 'Charleston',
    operator: 'KHAT Express Air Cargo',
    address: '3400 Air Cargo Lane Ste A',
    city: 'Charleston',
    state: 'SC',
    zip: '29418',
    hours: { 'Mon-Fri': '9:00am-6:00pm', 'Sat-Sun': 'Closed' },
  },
  {
    code: 'CLT',
    name: 'Charlotte',
    operator: 'JetStream Ground Services, Inc.',
    address: '4402 Yorkmont Rd',
    city: 'Charlotte',
    state: 'NC',
    zip: '28208',
    hours: { 'Mon-Fri': '4:00am-11:30pm', 'Sat': '6:00am-6:00pm', 'Sun': '9:30am-6:00pm' },
  },
  {
    code: 'CLE',
    name: 'Cleveland',
    address: '6072 Cargo Rd',
    city: 'Cleveland',
    state: 'OH',
    zip: '44135',
    hours: { 'Mon-Fri': '6:30am-10:30pm', 'Sat': '9:15am-5:15pm', 'Sun': '2:30pm-10:00pm' },
  },
  {
    code: 'CMH',
    name: 'Columbus',
    address: '4750 E 5th Ave Cargo Bay D',
    city: 'Columbus',
    state: 'OH',
    zip: '43219',
    hours: { 'Mon-Fri': '6:00am-12:00am', 'Sat-Sun': '9:00am-5:00pm' },
  },
  {
    code: 'CRP',
    name: 'Corpus Christi',
    operator: 'Signature Flight Support',
    address: '586 Hanger Lane',
    city: 'Corpus Christi',
    state: 'TX',
    zip: '78406',
    hours: { 'Mon-Fri': '6:00am-9:00pm', 'Sat': '7:00am-12:00pm', 'Sun': 'Closed' },
  },
  {
    code: 'DAL',
    name: 'Dallas',
    address: '7510 Aviation Place Ste 110',
    city: 'Dallas',
    state: 'TX',
    zip: '75235',
    hours: { 'Mon-Fri': '4:30am-1:30am', 'Sat': '4:30am-12:00am', 'Sun': '4:30am-1:30am' },
  },
  {
    code: 'DAY',
    name: 'Dayton',
    operator: 'Wright Bros. Aero, Inc',
    address: '3600 McCauley Dr',
    city: 'Vandalia',
    state: 'OH',
    zip: '45377',
    hours: { 'Mon-Fri': '5:00am-9:30pm', 'Sat-Sun': 'Closed' },
  },
  {
    code: 'DEN',
    name: 'Denver',
    address: '7640 N Undergrove St (Suite E)',
    city: 'Denver',
    state: 'CO',
    zip: '80249',
    hours: { 'Mon-Sat': '4:30am-12:00am', 'Sun': '5:00am-12:00am' },
  },
  {
    code: 'DTW',
    name: 'Detroit',
    address: '614 E Service Dr',
    city: 'Detroit',
    state: 'MI',
    zip: '48242',
    hours: { 'Mon-Fri': '4:45am-1:00am', 'Sat-Sun': '9:00am-5:00pm' },
  },
  {
    code: 'ELP',
    name: 'El Paso',
    address: '6435 Convair Rd',
    city: 'El Paso',
    state: 'TX',
    zip: '79925',
    hours: { 'Mon-Fri': '5:15am-10:30pm', 'Sat': '8:30am-7:30pm', 'Sun': '8:30am-8:30pm' },
  },
  {
    code: 'FLL',
    name: 'Fort Lauderdale/Hollywood',
    address: 'Bay 5, 3519 SW 2nd Ave',
    city: 'Ft. Lauderdale',
    state: 'FL',
    zip: '33315',
    hours: { 'Mon-Fri': '5:15am-11:30pm', 'Sat-Sun': '5:15am-9:45pm' },
  },
  {
    code: 'RSW',
    name: 'Fort Myers/Naples',
    operator: 'Airport Terminal Services',
    address: '11850 Regional Lane',
    city: 'Ft. Myers',
    state: 'FL',
    zip: '33913',
    hours: { 'Mon-Fri': '5:00am-10:00pm', 'Sat-Sun': '8:00am-4:00pm' },
  },
  {
    code: 'GRR',
    name: 'Grand Rapids',
    operator: 'Servisair',
    address: '5500 44th Street Southeast Building 401',
    city: 'Grand Rapids',
    state: 'MI',
    zip: '49512',
    hours: { 'Mon-Fri': '5:30am-10:30pm', 'Sat-Sun': 'Closed' },
  },
  {
    code: 'GSP',
    name: 'Greenville/Spartanburg',
    operator: 'Majestic Terminal Services',
    address: '1900 GSP Dr Ste 10',
    city: 'Greer',
    state: 'SC',
    zip: '29651',
    hours: { 'Mon-Fri': '9:00am-6:00pm', 'Sat-Sun': 'Closed' },
  },
  {
    code: 'HRL',
    name: 'Harlingen',
    address: '2730 Airport Dr',
    city: 'Harlingen',
    state: 'TX',
    zip: '78550',
    hours: { 'Mon-Fri': '5:00am-12:00am', 'Sat': '8:00am-5:00pm', 'Sun': '8:30am-5:00pm' },
  },
  {
    code: 'MDT',
    name: 'Harrisburg',
    operator: 'Freight Land Sky, Inc.',
    address: '1000 Sycamore St',
    city: 'Harrisburg',
    state: 'PA',
    zip: '17104',
    hours: { 'Mon-Fri': '7:30am-8:00pm', 'Sat-Sun': 'Closed' },
  },
  {
    code: 'BDL',
    name: 'Hartford/Springfield',
    address: 'Roncari Cargo Complex, Air Cargo East Drs 50-53, Bradley International Airport (BDL)',
    city: 'Windsor Locks',
    state: 'CT',
    zip: '06096',
    hours: { 'Mon-Fri': '5:00am-11:00pm', 'Sat-Sun': '5:00am-1:30pm' },
  },
  {
    code: 'ITO',
    name: 'Hilo',
    operator: 'Hawaiian Air Cargo',
    address: '50 Old General Lyman Field',
    city: 'Hilo',
    state: 'HI',
    zip: '96720',
    hours: { 'Mon-Fri': '7:00am-7:30pm', 'Sat-Sun': '7:00am-1:00pm' },
  },
  {
    code: 'HNL',
    name: 'Honolulu',
    operator: 'Hawaiian Air Cargo',
    address: '1 Elliott St',
    city: 'Honolulu',
    state: 'HI',
    zip: '96819',
    hours: { 'Mon-Sun': '7:00am-7:30pm' },
  },
  {
    code: 'HOU',
    name: 'Houston Hobby',
    address: '7910 Airport Blvd',
    city: 'Houston',
    state: 'TX',
    zip: '77061',
    hours: { 'Mon': '4:00am-12:00am', 'Tue-Fri': 'Open 24 hours', 'Sat': '12:00am-12:00am', 'Sun': '5:00am-12:00am' },
  },
  {
    code: 'IAH',
    name: 'Houston Intercontinental',
    operator: 'Accelerated, Inc.',
    address: '3340B Greens Rd Ste 600',
    city: 'Houston',
    state: 'TX',
    zip: '77032',
    hours: { 'Mon-Fri': '8:00am-10:00pm', 'Sat': '8:00am-12:00pm', 'Sun': 'Closed' },
  },
  {
    code: 'IND',
    name: 'Indianapolis',
    address: '7899 S Service Rd',
    city: 'Indianapolis',
    state: 'IN',
    zip: '46241',
    hours: { 'Mon-Fri': '4:30am-12:30am', 'Sat-Sun': '9:00am-5:00pm' },
  },
  {
    code: 'JAX',
    name: 'Jacksonville',
    operator: 'Majestic Terminal Services',
    address: '13824 Thomas Imeson Ave (Bay 26)',
    city: 'Jacksonville',
    state: 'FL',
    zip: '32218',
    hours: { 'Mon-Fri': '5:00am-10:30pm', 'Sat': '5:30am-10:30pm', 'Sun': 'Closed' },
  },
  {
    code: 'MCI',
    name: 'Kansas City',
    address: '992 Mexico City Ave',
    city: 'Kansas City',
    state: 'MO',
    zip: '64153',
    hours: { 'Mon-Fri': '5:00am-12:00am', 'Sat-Sun': '6:00am-10:30pm' },
  },
  {
    code: 'KOA',
    name: 'Kona',
    operator: 'Hawaiian Air Cargo',
    address: '73-370 Kupipi Street',
    city: 'Kailua-Kona',
    state: 'HI',
    zip: '96740',
    hours: { 'Mon-Fri': '5:00am-7:00pm', 'Sat-Sun': '5:00am-1:00pm' },
  },
  {
    code: 'LAS',
    name: 'Las Vegas',
    address: '6055 Surrey St Ste 121',
    city: 'Las Vegas',
    state: 'NV',
    zip: '89119',
    hours: { 'Mon-Fri': '4:30am-11:30pm', 'Sat-Sun': '6:00am-9:30pm' },
  },
  {
    code: 'LIH',
    name: 'Lihue',
    operator: 'Hawaiian Air Cargo',
    address: '3651 Ahukini Street',
    city: 'Lihue',
    state: 'HI',
    zip: '96766',
    hours: { 'Mon-Fri': '6:00am-7:30pm', 'Sat-Sun': '6:00am-1:00pm' },
  },
  {
    code: 'LIT',
    name: 'Little Rock',
    address: '1100 Temple Rd',
    city: 'Little Rock',
    state: 'AR',
    zip: '72202',
    hours: { 'Mon-Fri': '4:30am-11:30pm', 'Sat-Sun': '8:00am-4:30pm' },
  },
  {
    code: 'ISP',
    name: 'Long Island/Islip',
    address: '201 Clark Dr',
    city: 'Ronkonkoma',
    state: 'NY',
    zip: '11779',
    hours: { 'Mon-Fri': '5:30am-11:00pm', 'Sat-Sun': '7:00am-3:00pm' },
  },
  {
    code: 'LAX',
    name: 'Los Angeles',
    address: '5600 W Century Blvd',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90045',
    hours: { 'Mon': '4:30am-12:00am', 'Tue-Fri': 'Open 24 hours', 'Sat': '12:00am-12:00am', 'Sun': '5:00am-12:00am' },
  },
  {
    code: 'SDF',
    name: 'Louisville',
    address: '4650 Air Freight Dr (Bay 14)',
    city: 'Louisville',
    state: 'KY',
    zip: '40209',
    hours: { 'Mon-Fri': '5:00am-1:00am', 'Sat': '5:00am-10:00pm', 'Sun': '5:00am-1:00am' },
  },
  {
    code: 'LBB',
    name: 'Lubbock',
    address: '5401 N Martin L King Blvd',
    city: 'Lubbock',
    state: 'TX',
    zip: '79403',
    hours: { 'Mon-Fri': '5:30am-10:30pm', 'Sat-Sun': '8:00am-4:30pm' },
  },
  {
    code: 'MHT',
    name: 'Manchester',
    operator: 'Air General, Inc.',
    address: '26 Commerce Avenue',
    city: 'Londonderry',
    state: 'NH',
    zip: '03053',
    hours: { 'Mon-Fri': '5:00am-10:00pm', 'Sat-Sun': 'Closed' },
  },
  {
    code: 'OGG',
    name: 'Maui',
    operator: 'Hawaiian Air Cargo',
    address: 'c/o 870 Haleakala Highway',
    city: 'Kahului',
    state: 'HI',
    zip: '96732',
    hours: { 'Mon-Fri': '6:00am-7:00pm', 'Sat-Sun': '6:00am-1:00pm' },
  },
  {
    code: 'MEM',
    name: 'Memphis',
    operator: 'Air General',
    address: '2545 Winchester Road, Memphis International Airport Cargo Bldg #2',
    city: 'Memphis',
    state: 'TN',
    zip: '38116',
    hours: { 'Mon-Fri': '5:00am-11:00pm', 'Sat': '5:00am-1:00pm', 'Sun': '8:00am-4:30pm' },
  },
  {
    code: 'MIA',
    name: 'Miami',
    operator: 'Swissport Cargo Services',
    address: '1851 NW 68th Avenue, Cargo Building 706 STE 225',
    city: 'Miami',
    state: 'FL',
    zip: '33126',
    hours: { 'Mon-Sun': '6:00am-6:00pm' },
  },
  {
    code: 'MAF',
    name: 'Midland/Odessa',
    address: '2701 Earhart Dr',
    city: 'Midland',
    state: 'TX',
    zip: '79711',
    hours: { 'Mon-Fri': '5:15am-10:15pm', 'Sat': '8:15am-4:45pm', 'Sun': '10:30am-7:00pm' },
  },
  {
    code: 'MKE',
    name: 'Milwaukee',
    operator: 'Majestic Terminal Services',
    address: '311 West Air Cargo Way',
    city: 'Milwaukee',
    state: 'WI',
    zip: '53207',
    hours: { 'Mon-Fri': '5:00am-12:00am', 'Sat': '6:00am-2:00pm', 'Sun': 'Closed' },
  },
  {
    code: 'BNA',
    name: 'Nashville',
    address: '969 Air Service Rd',
    city: 'Nashville',
    state: 'TN',
    zip: '37214',
    hours: { 'Mon-Fri': '5:15am-12:00am', 'Sat-Sun': '5:15am-9:30pm' },
  },
  {
    code: 'MSY',
    name: 'New Orleans',
    address: '200 Crofton Rd, East Access Bldg 3 Ste 101',
    city: 'Kenner',
    state: 'LA',
    zip: '70062',
    hours: { 'Mon-Fri': '4:45am-12:30am', 'Sat-Sun': '4:45am-5:30pm' },
  },
  {
    code: 'LGA',
    name: 'New York LaGuardia',
    operator: 'JetStream Ground Services, Inc.',
    address: 'Cargo Building Hangar 5A',
    city: 'Flushing',
    state: 'NY',
    zip: '11371',
    hours: { 'Mon': '5:00am-12:00am', 'Tue-Thu': 'Open 24 hours', 'Fri': '12:00am-12:00am', 'Sat-Sun': '5:00am-11:00pm' },
  },
  {
    code: 'ORF',
    name: 'Norfolk/Virginia Beach',
    operator: 'Majestic Terminal Services',
    address: '6000 Robin Hood Rd',
    city: 'Norfolk',
    state: 'VA',
    zip: '23518',
    hours: { 'Mon-Fri': '5:30am-9:30pm', 'Sat': '9:00am-9:00pm', 'Sun': 'Closed' },
  },
  {
    code: 'OAK',
    name: 'Oakland',
    address: '10 Alan Shepard Way',
    city: 'Oakland',
    state: 'CA',
    zip: '94621',
    hours: { 'Mon-Fri': '4:30am-12:00am', 'Sat': '4:30am-11:00pm', 'Sun': '6:00am-11:00pm' },
  },
  {
    code: 'OKC',
    name: 'Oklahoma City',
    address: 'Bay Q, 7130 Air Cargo Rd',
    city: 'Oklahoma City',
    state: 'OK',
    zip: '73159',
    hours: { 'Mon-Wed': '5:00am-12:30am', 'Thu-Fri': '5:00am-9:30pm', 'Sat-Sun': '5:30am-2:00pm' },
  },
  {
    code: 'OMA',
    name: 'Omaha',
    operator: 'Majestic Terminal Services',
    address: '5233 E Boeing Court',
    city: 'Omaha',
    state: 'NE',
    zip: '68110',
    hours: { 'Mon-Fri': '5:00am-11:00pm', 'Sat': '5:00am-2:30pm', 'Sun': 'Closed' },
  },
  {
    code: 'SNA',
    name: 'Orange County',
    operator: 'Majestic Terminal Services',
    address: 'Bay 5, 3000 B Airway Ave',
    city: 'Costa Mesa',
    state: 'CA',
    zip: '92626',
    hours: { 'Mon-Fri': '5:00am-11:00pm', 'Sat': '8:00am-10:00pm', 'Sun': 'Closed' },
  },
  {
    code: 'MCO',
    name: 'Orlando',
    address: '8835 Bear Rd',
    city: 'Orlando',
    state: 'FL',
    zip: '32827',
    hours: { 'Mon-Fri': '5:00am-1:00am', 'Sat-Sun': '6:00am-11:00pm' },
  },
  {
    code: 'PHL',
    name: 'Philadelphia',
    address: 'Philadelphia International Airport, Cargo City Bldg C-2 Doors 16-18',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19153',
    hours: { 'Mon-Fri': '5:00am-1:00am', 'Sat-Sun': '6:00am-2:00pm' },
  },
  {
    code: 'PHX',
    name: 'Phoenix',
    address: '1251 S 25th PIace Ste 16',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85034',
    hours: { 'Mon-Fri': '4:15am-1:30am', 'Sat': '5:00am-12:45am', 'Sun': '5:00am-1:30am' },
  },
  {
    code: 'PIT',
    name: 'Pittsburgh',
    operator: 'Worldwide Flight Services',
    address: 'Pittsburgh International Airport, 3000 Halverson Rd, Building 846',
    city: 'Pittsburgh',
    state: 'PA',
    zip: '15231',
    hours: { 'Mon-Fri': '6:00am-11:00pm', 'Sat-Sun': '9:00am-5:00pm' },
  },
  {
    code: 'PDX',
    name: 'Portland',
    address: '7808 NE Air Cargo Rd',
    city: 'Portland',
    state: 'OR',
    zip: '97218',
    hours: { 'Mon-Fri': '5:00am-12:00am', 'Sat': '5:00am-11:00pm', 'Sun': '5:00am-12:00am' },
  },
  {
    code: 'PVD',
    name: 'Providence',
    operator: 'Jetstream Ground Services, Inc.',
    address: 'T.F. Green Airport 2000 Post Rd',
    city: 'Warwick',
    state: 'RI',
    zip: '02886',
    hours: { 'Mon-Fri': '6:00am-10:30pm', 'Sat': '8:00am-4:00pm', 'Sun': 'Closed' },
  },
  {
    code: 'RDU',
    name: 'Raleigh/Durham',
    address: '1035 Airside Dr Bldg 1R Unit 1101',
    city: 'Morrisville',
    state: 'NC',
    zip: '27560',
    hours: { 'Mon-Fri': '5:00am-12:30am', 'Sat': '5:30am-10:00pm', 'Sun': '5:30am-8:30pm' },
  },
  {
    code: 'RNO',
    name: 'Reno',
    address: '1395 Air Cargo Way #125',
    city: 'Reno',
    state: 'NV',
    zip: '89502',
    hours: { 'Mon-Fri': '5:30am-11:00pm', 'Sat-Sun': '8:30am-5:00pm' },
  },
  {
    code: 'RIC',
    name: 'Richmond',
    operator: 'Commonwealth Cargo, Inc.',
    address: '5501 Fox Rd Cargo Bldg 5',
    city: 'Richmond',
    state: 'VA',
    zip: '23250',
    hours: { 'Mon-Fri': '5:30am-8:00pm', 'Sat': '5:30am-12:00pm', 'Sun': 'Closed' },
  },
  {
    code: 'ROC',
    name: 'Rochester',
    operator: 'JetStream Ground Services, Inc.',
    address: '1200 Brooks Ave',
    city: 'Rochester',
    state: 'NY',
    zip: '14624',
    hours: { 'Mon-Fri': '5:00am-11:00pm', 'Sat-Sun': 'Closed' },
  },
  {
    code: 'SMF',
    name: 'Sacramento',
    address: '6733 Lindbergh Dr Ste A',
    city: 'Sacramento',
    state: 'CA',
    zip: '95837',
    hours: { 'Mon-Fri': '5:00am-11:30pm', 'Sat': '5:30am-5:30pm', 'Sun': '5:30am-4:30pm' },
  },
  {
    code: 'SLC',
    name: 'Salt Lake City',
    address: 'Cargo Terminal, 462 N 3700 West',
    city: 'Salt Lake City',
    state: 'UT',
    zip: '84122',
    hours: { 'Mon-Fri': '5:15am-11:30pm', 'Sat': '6:15am-11:00pm', 'Sun': '8:15am-11:30pm' },
  },
  {
    code: 'SAT',
    name: 'San Antonio',
    address: '10000 John Saunders',
    city: 'San Antonio',
    state: 'TX',
    zip: '78216',
    hours: { 'Mon-Fri': '4:15am-12:00am', 'Sat-Sun': '4:15am-11:00pm' },
  },
  {
    code: 'SAN',
    name: 'San Diego',
    address: '2361 Airlane Rd',
    city: 'San Diego',
    state: 'CA',
    zip: '92101',
    hours: { 'Mon-Fri': '5:30am-11:30pm', 'Sat': '5:30am-10:30pm', 'Sun': '9:00am-5:00pm' },
  },
  {
    code: 'SFO',
    name: 'San Francisco',
    address: 'San Francisco International Airport, 606 N.McDonnell Rd',
    city: 'San Francisco',
    state: 'CA',
    zip: '94128',
    hours: { 'Mon-Fri': '5:30am-12:00am', 'Sat': '5:30am-9:00pm', 'Sun': '10:00am-6:00pm' },
  },
  {
    code: 'SJC',
    name: 'San Jose',
    address: '1521 Airport Blvd',
    city: 'San Jose',
    state: 'CA',
    zip: '95110',
    hours: { 'Mon-Fri': '5:30am-11:00pm', 'Sat-Sun': '10:00am-6:00pm' },
  },
  {
    code: 'SJU',
    name: 'San Juan',
    operator: 'Grnd Motive Dependable Airline Service',
    address: 'Cargo Service Corp. Bldg, Suite E-5 Base Muniz. Luis Munoz Marin Intl airport',
    city: 'Carolina',
    state: 'PR',
    zip: '00937',
    hours: { 'Mon-Sun': '4:30am-10:30pm' },
  },
  {
    code: 'SEA',
    name: 'Seattle/Tacoma',
    address: '16215 Air Cargo Rd',
    city: 'Seattle',
    state: 'WA',
    zip: '98158',
    hours: { 'Mon-Fri': '5:00am-12:00am', 'Sat-Sun': '6:00am-10:00pm' },
  },
  {
    code: 'GEG',
    name: 'Spokane',
    operator: 'Majestic Terminal Services',
    address: '2933 S Flint Rd',
    city: 'Spokane',
    state: 'WA',
    zip: '99224',
    hours: { 'Mon-Fri': '5:30am-11:30pm', 'Sat': '9:30am-4:00pm', 'Sun': 'Closed' },
  },
  {
    code: 'STL',
    name: 'St. Louis',
    address: '9813 Air Cargo Rd',
    city: 'St. Louis',
    state: 'MO',
    zip: '63134',
    hours: { 'Mon-Fri': '4:30am-1:00am', 'Sat-Sun': '5:00am-9:30pm' },
  },
  {
    code: 'TPA',
    name: 'Tampa',
    address: '4662 Air Cargo Rd Ste 1800',
    city: 'Tampa',
    state: 'FL',
    zip: '33614',
    hours: { 'Mon-Fri': '4:30am-12:00am', 'Sat': '5:00am-9:00pm', 'Sun': '5:00am-10:30pm' },
  },
  {
    code: 'TUS',
    name: 'Tucson',
    address: '2600 E Los Reales Rd Bldg 3',
    city: 'Tucson',
    state: 'AZ',
    zip: '85756',
    hours: { 'Mon-Fri': '4:30am-12:00am', 'Sat': '5:00am-10:00pm', 'Sun': '7:00am-12:00am' },
  },
  {
    code: 'TUL',
    name: 'Tulsa',
    address: '2139 Cargo Rd',
    city: 'Tulsa',
    state: 'OK',
    zip: '74115',
    hours: { 'Mon-Fri': '5:00am-10:00pm', 'Sat-Sun': '7:00am-3:30pm' },
  },
  {
    code: 'IAD',
    name: 'Washington Dulles',
    operator: 'Worldwide Flight Services',
    address: '23703 B Air Freight Lane, Cargo Bldg 6',
    city: 'Sterling',
    state: 'VA',
    zip: '20166',
    hours: { 'Mon-Sun': '5:00am-10:00pm' },
  },
  {
    code: 'DCA',
    name: 'Washington Reagan',
    operator: 'Air General',
    address: '100 Air Cargo Rd',
    city: 'Washington',
    state: 'DC',
    zip: '20001',
    hours: { 'Mon-Fri': '5:00am-10:00pm', 'Sat': '5:00am-2:00pm', 'Sun': 'Closed' },
  },
  {
    code: 'PBI',
    name: 'West Palm Beach',
    operator: 'Centerport, Inc',
    address: '1301 North Perimeter Rd',
    city: 'West Palm Beach',
    state: 'FL',
    zip: '33406',
    hours: { 'Mon-Fri': '6:30am-7:00pm', 'Sat': '7:00am-1:00pm', 'Sun': 'Closed' },
  },
]

async function seedAirports() {
  console.log('🛫 Starting Southwest Cargo airport import...')
  console.log(`📍 Importing ${SOUTHWEST_CARGO_AIRPORTS.length} airports from definitive list (Oct 17, 2025)`)
  console.log('=' .repeat(80))

  let successCount = 0
  let errorCount = 0
  const errors: string[] = []

  for (const airport of SOUTHWEST_CARGO_AIRPORTS) {
    try {
      await prisma.airport.upsert({
        where: { code: airport.code },
        update: {
          name: airport.name,
          carrier: Carrier.SOUTHWEST_CARGO,
          operator: airport.operator || null,
          address: airport.address,
          city: airport.city,
          state: airport.state,
          zip: airport.zip,
          hours: airport.hours,
          isActive: true,
          updatedAt: new Date(),
        },
        create: {
          id: randomUUID(),
          code: airport.code,
          name: airport.name,
          carrier: Carrier.SOUTHWEST_CARGO,
          operator: airport.operator || null,
          address: airport.address,
          city: airport.city,
          state: airport.state,
          zip: airport.zip,
          hours: airport.hours,
          isActive: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      })

      successCount++
      const operatorText = airport.operator ? ` (Operated by ${airport.operator})` : ''
      console.log(`✅ ${successCount}/82: ${airport.code} - ${airport.name}, ${airport.state}${operatorText}`)
    } catch (error) {
      errorCount++
      const errorMsg = `${airport.code}: ${error instanceof Error ? error.message : String(error)}`
      errors.push(errorMsg)
      console.error(`❌ Failed: ${errorMsg}`)
    }
  }

  console.log('=' .repeat(80))
  console.log(`
🎉 Airport import complete!
✅ Success: ${successCount} airports
❌ Failed: ${errorCount} airports
📊 Total: ${SOUTHWEST_CARGO_AIRPORTS.length} airports
`)

  if (errors.length > 0) {
    console.log('⚠️  Errors encountered:')
    errors.forEach((err, i) => {
      console.log(`   ${i + 1}. ${err}`)
    })
  }

  if (successCount === 82) {
    console.log('✅ ALL 82 AIRPORTS SUCCESSFULLY IMPORTED!')
    console.log('📍 Next steps:')
    console.log('   1. Verify: npx tsx diagnose-southwest-issue.ts')
    console.log('   2. Test locations page: http://localhost:3020/locations')
    console.log('   3. Test checkout: Add product → Checkout → Select Southwest Cargo')
  }
}

// Run the seeder
seedAirports()
  .catch((e) => {
    console.error('❌ Error seeding airports:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
