# Alertmanager configuration for GangRun Printing
global:
  smtp_smarthost: 'smtp.resend.com:587'
  smtp_from: 'alerts@gangrunprinting.com'
  smtp_auth_username: 'resend'
  smtp_auth_password: '${RESEND_API_KEY}'
  smtp_require_tls: true

# Templates for alert formatting
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route configuration
route:
  group_by: ['alertname', 'severity', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'

  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m

    # Business alerts - business hours only
    - match:
        service: business
      receiver: 'business-alerts'
      group_interval: 30m
      repeat_interval: 4h

    # System alerts - standard notification
    - match:
        service: system
      receiver: 'system-alerts'
      repeat_interval: 2h

    # Database alerts - high priority
    - match:
        service: database
      receiver: 'database-alerts'
      repeat_interval: 30m

    # SSL certificate alerts
    - match:
        service: ssl
      receiver: 'ssl-alerts'
      repeat_interval: 24h

receivers:
  # Default receiver
  - name: 'default'
    email_configs:
      - to: 'admin@gangrunprinting.com'
        subject: '[GangRun] {{ .Status | title }} - {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Severity:** {{ .Labels.severity }}
          **Service:** {{ .Labels.service }}
          **Started:** {{ .StartsAt | date "2006-01-02 15:04:05 MST" }}
          {{ if .EndsAt }}**Ended:** {{ .EndsAt | date "2006-01-02 15:04:05 MST" }}{{ end }}

          **Labels:**
          {{ range .Labels.SortedPairs }}  {{ .Name }}: {{ .Value }}
          {{ end }}
          {{ end }}

  # Critical alerts - multiple channels
  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@gangrunprinting.com,alerts@gangrunprinting.com'
        subject: '[CRITICAL] GangRun Printing - {{ .GroupLabels.alertname }}'
        body: |
          🚨 **CRITICAL ALERT** 🚨

          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Service:** {{ .Labels.service }}
          **Instance:** {{ .Labels.instance }}
          **Started:** {{ .StartsAt | date "2006-01-02 15:04:05 MST" }}

          **Immediate Action Required!**

          **Labels:**
          {{ range .Labels.SortedPairs }}  {{ .Name }}: {{ .Value }}
          {{ end }}
          {{ end }}

          Please investigate immediately and acknowledge this alert.
        headers:
          X-Priority: '1'

  # Business alerts
  - name: 'business-alerts'
    email_configs:
      - to: 'business@gangrunprinting.com,admin@gangrunprinting.com'
        subject: '[BUSINESS] GangRun Printing - {{ .GroupLabels.alertname }}'
        body: |
          📊 **Business Alert** 📊

          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Started:** {{ .StartsAt | date "2006-01-02 15:04:05 MST" }}

          This alert indicates a potential impact on business operations.
          Please review the metrics and take appropriate action.

          **Labels:**
          {{ range .Labels.SortedPairs }}  {{ .Name }}: {{ .Value }}
          {{ end }}
          {{ end }}

  # System alerts
  - name: 'system-alerts'
    email_configs:
      - to: 'admin@gangrunprinting.com'
        subject: '[SYSTEM] GangRun Printing - {{ .GroupLabels.alertname }}'
        body: |
          🖥️ **System Alert** 🖥️

          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Instance:** {{ .Labels.instance }}
          **Started:** {{ .StartsAt | date "2006-01-02 15:04:05 MST" }}

          **Labels:**
          {{ range .Labels.SortedPairs }}  {{ .Name }}: {{ .Value }}
          {{ end }}
          {{ end }}

  # Database alerts
  - name: 'database-alerts'
    email_configs:
      - to: 'admin@gangrunprinting.com'
        subject: '[DATABASE] GangRun Printing - {{ .GroupLabels.alertname }}'
        body: |
          🗄️ **Database Alert** 🗄️

          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Started:** {{ .StartsAt | date "2006-01-02 15:04:05 MST" }}

          Database performance or availability may be impacted.
          Please check database health immediately.

          **Labels:**
          {{ range .Labels.SortedPairs }}  {{ .Name }}: {{ .Value }}
          {{ end }}
          {{ end }}

  # SSL certificate alerts
  - name: 'ssl-alerts'
    email_configs:
      - to: 'admin@gangrunprinting.com'
        subject: '[SSL] GangRun Printing - {{ .GroupLabels.alertname }}'
        body: |
          🔒 **SSL Certificate Alert** 🔒

          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Domain:** {{ .Labels.instance }}
          **Started:** {{ .StartsAt | date "2006-01-02 15:04:05 MST" }}

          SSL certificate requires attention to maintain secure connections.

          **Labels:**
          {{ range .Labels.SortedPairs }}  {{ .Name }}: {{ .Value }}
          {{ end }}
          {{ end }}

# Inhibition rules to suppress redundant alerts
inhibit_rules:
  # Suppress warning alerts when critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

  # Suppress individual service alerts when the entire instance is down
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '(High.*|Slow.*|Database.*)'
    equal: ['instance']

  # Suppress SSL expiry warnings when certificate has already expired
  - source_match:
      alertname: 'SSLCertificateExpired'
    target_match:
      alertname: 'SSLCertificateExpiringSoon'
    equal: ['instance']
