#!/bin/bash

# GangRun Printing Production Deployment Script
# This script provides instructions and verification for Dokploy deployment

echo "================================================"
echo "GangRun Printing - Production Deployment"
echo "================================================"
echo ""
echo "Latest Commit: $(git rev-parse --short HEAD)"
echo "Branch: $(git branch --show-current)"
echo "Commit Message: $(git log -1 --pretty=%B)"
echo ""
echo "================================================"
echo "DEPLOYMENT INSTRUCTIONS FOR DOKPLOY"
echo "================================================"
echo ""
echo "1. Open Dokploy Dashboard:"
echo "   URL: http://72.60.28.175:3000"
echo ""
echo "2. Navigate to:"
echo "   - Project: gangrunprinting"
echo "   - Application: GangRun Printing"
echo ""
echo "3. In the Application Settings, verify environment variables are set:"
echo "   ✓ DATABASE_URL"
echo "   ✓ AUTH_SECRET"
echo "   ✓ SQUARE_ACCESS_TOKEN"
echo "   ✓ SENDGRID_API_KEY"
echo "   ✓ N8N_WEBHOOK_URL"
echo "   ✓ VAPID_PUBLIC_KEY"
echo "   ✓ VAPID_PRIVATE_KEY"
echo ""
echo "4. Click 'Deploy' button and select:"
echo "   - Source: GitHub"
echo "   - Branch: main"
echo "   - Commit: $(git rev-parse HEAD)"
echo ""
echo "5. Monitor deployment logs for completion"
echo ""
echo "================================================"
echo "POST-DEPLOYMENT VERIFICATION"
echo "================================================"
echo ""
echo "After deployment completes, verify these endpoints:"
echo ""
echo "Testing production endpoints..."
echo ""

# Function to check endpoint
check_endpoint() {
    local url=$1
    local name=$2
    
    # Use curl to check if endpoint responds
    if curl -s -o /dev/null -w "%{http_code}" "$url" | grep -q "200\|301\|302\|304"; then
        echo "✅ $name: $url"
    else
        echo "❌ $name: $url (Check after deployment)"
    fi
}

# Check production endpoints (will fail until deployed)
echo "Production Endpoints Status:"
check_endpoint "https://gangrunprinting.com" "Homepage"
check_endpoint "https://gangrunprinting.com/products" "Products"
check_endpoint "https://gangrunprinting.com/contact" "Contact"
check_endpoint "https://gangrunprinting.com/auth/signup" "Signup"
check_endpoint "https://gangrunprinting.com/about" "About"
check_endpoint "https://gangrunprinting.com/help-center" "Help Center"

echo ""
echo "================================================"
echo "DATABASE MIGRATION COMMANDS"
echo "================================================"
echo ""
echo "After deployment, run these in Dokploy terminal:"
echo ""
echo "1. Access the application container in Dokploy"
echo "2. Run migrations:"
echo "   npx prisma migrate deploy"
echo "   npx prisma db push"
echo ""
echo "================================================"
echo "QUICK DEPLOYMENT CHECKLIST"
echo "================================================"
echo ""
echo "□ Dokploy deployment triggered"
echo "□ Build logs show success"
echo "□ Application container running"
echo "□ Database migrations completed"
echo "□ Domain accessible (https://gangrunprinting.com)"
echo "□ SSL certificate active"
echo "□ Test order placement works"
echo "□ Admin dashboard accessible"
echo ""
echo "================================================"
echo "SUPPORT"
echo "================================================"
echo ""
echo "If deployment fails, check:"
echo "1. Dokploy application logs"
echo "2. PostgreSQL container status"
echo "3. Environment variables in Dokploy"
echo "4. GitHub repository access"
echo ""
echo "Ready to deploy? Go to: http://72.60.28.175:3000"
echo ""